### ISSUE TITLE
1.20 TODO List

### ISSUE THREAD

**Issue by Superice666** [PowerNukkitX/PowerNukkitX#1225]
- [ ] 新方块
  - [ ] [竹板](https://wiki.biligame.com/mc/%E7%AB%B9%E6%9D%BF)，及其对应的：
    - [ ] [按钮](https://wiki.biligame.com/mc/%E6%8C%89%E9%92%AE)
    - [ ] [告示牌](https://wiki.biligame.com/mc/%E5%91%8A%E7%A4%BA%E7%89%8C)
    - [ ] [门](https://wiki.biligame.com/mc/%E9%97%A8)
    - [ ] [栅栏](https://wiki.biligame.com/mc/%E6%A0%85%E6%A0%8F)
    - [ ] [栅栏门](https://wiki.biligame.com/mc/%E6%A0%85%E6%A0%8F%E9%97%A8)
    - [ ] [压力板](https://wiki.biligame.com/mc/%E5%8E%8B%E5%8A%9B%E6%9D%BF)
    - [ ] [台阶](https://wiki.biligame.com/mc/%E5%8F%B0%E9%98%B6)
    - [ ] [楼梯](https://wiki.biligame.com/mc/%E6%A5%BC%E6%A2%AF)
    - [ ] [活板门](https://wiki.biligame.com/mc/%E6%B4%BB%E6%9D%BF%E9%97%A8)
    - [ ] [竹筏](https://wiki.biligame.com/mc/%E7%AB%B9%E7%AD%8F)
    - [ ] [运输竹筏](https://wiki.biligame.com/mc/%E8%BF%90%E8%BE%93%E7%AB%B9%E7%AD%8F)
  - [ ] [竹马赛克](https://wiki.biligame.com/mc/%E7%AB%B9%E9%A9%AC%E8%B5%9B%E5%85%8B)
  - [ ] [竹块](https://wiki.biligame.com/mc/%E7%AB%B9%E5%9D%97)
  - [ ] [校频幽匿感测体](https://wiki.biligame.com/mc/%E6%A0%A1%E9%A2%91%E5%B9%BD%E5%8C%BF%E6%84%9F%E6%B5%8B%E4%BD%93)
  - [ ] [雕纹书架](https://wiki.biligame.com/mc/%E9%9B%95%E7%BA%B9%E4%B9%A6%E6%9E%B6)
  - [ ] [悬挂式告示牌](https://wiki.biligame.com/mc/%E6%82%AC%E6%8C%82%E5%BC%8F%E5%91%8A%E7%A4%BA%E7%89%8C)
  - [x] [樱花树叶](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%A0%91%E5%8F%B6)
    - [ ] 蜜蜂将其视为花
  - [x] [樱花原木](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E5%8E%9F%E6%9C%A8)
  - [ ] [樱花木板](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%9C%A8%E6%9D%BF)，及其对应的
    - [ ] [按钮](https://wiki.biligame.com/mc/%E6%8C%89%E9%92%AE)
    - [ ] [门](https://wiki.biligame.com/mc/%E9%97%A8)
    - [ ] [栅栏](https://wiki.biligame.com/mc/%E6%A0%85%E6%A0%8F)
    - [ ] [栅栏门](https://wiki.biligame.com/mc/%E6%A0%85%E6%A0%8F%E9%97%A8)
    - [ ] [压力板](https://wiki.biligame.com/mc/%E5%8E%8B%E5%8A%9B%E6%9D%BF)
    - [ ] [告示牌](https://wiki.biligame.com/mc/%E5%91%8A%E7%A4%BA%E7%89%8C)
    - [ ] [台阶](https://wiki.biligame.com/mc/%E5%8F%B0%E9%98%B6)
    - [ ] [楼梯](https://wiki.biligame.com/mc/%E6%A5%BC%E6%A2%AF)
    - [ ] [活板门](https://wiki.biligame.com/mc/%E6%B4%BB%E6%9D%BF%E9%97%A8)
    - [ ] [船](https://wiki.biligame.com/mc/%E8%88%B9)
    - [ ] [运输船](https://wiki.biligame.com/mc/%E8%BF%90%E8%BE%93%E8%88%B9)
  - [x] [樱花树苗](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%A0%91%E8%8B%97)
    - [ ] 可以自然长成樱花树
    - [ ] 可以被骨粉催熟
    - [ ] 可以放置在花盆中
  - [ ] [樱花木](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%9C%A8)
    - [ ] 去皮变种
  - [ ] [饰纹陶罐](https://wiki.biligame.com/mc/%E9%A5%B0%E7%BA%B9%E9%99%B6%E7%BD%90)
  - [ ] [粉红色花簇](https://wiki.biligame.com/mc/%E7%B2%89%E7%BA%A2%E8%89%B2%E8%8A%B1%E7%B0%87)
    - [ ] 蜜蜂将其视为花
  - [ ] [瓶子草植株](https://wiki.biligame.com/mc/%E7%93%B6%E5%AD%90%E8%8D%89%E6%A4%8D%E6%A0%AA)
  - [ ] [瓶子草](https://wiki.biligame.com/mc/%E7%93%B6%E5%AD%90%E8%8D%89)
  - [ ] [嗅探兽蛋](https://wiki.biligame.com/mc/%E5%97%85%E6%8E%A2%E5%85%BD%E8%9B%8B)
    - [ ] 可以从热带海底废墟中的可疑的沙子中获取
    - [ ] 两只[嗅探兽](https://wiki.biligame.com/mc/%E5%97%85%E6%8E%A2%E5%85%BD)繁殖后也会产下嗅探兽蛋。（需要先实现嗅探兽）
    - [ ] 放置于苔藓块上时会在大约10分钟后孵化。放置于其余方块上时的孵化时长约为20分钟。
  - [ ] [可疑的方块](https://wiki.biligame.com/mc/%E5%8F%AF%E7%96%91%E7%9A%84%E6%96%B9%E5%9D%97)
    - [ ] 可疑的沙子
    - [ ] 可疑的沙砾
    - [ ] 会在遗迹中自然生成
    - [ ] 可以用[刷子](https://wiki.biligame.com/mc/%E5%88%B7%E5%AD%90)刷扫出其中的物品
  - [ ] [火把花植株](https://wiki.biligame.com/mc/%E7%81%AB%E6%8A%8A%E8%8A%B1%E6%A4%8D%E6%A0%AA)
  - [ ] [火把花](https://wiki.biligame.com/mc/%E7%81%AB%E6%8A%8A%E8%8A%B1)
    - [ ] 可以放置在[花盆](https://wiki.biligame.com/mc/%E8%8A%B1%E7%9B%86)中
  - [ ] [猪灵的头](https://wiki.biligame.com/mc/%E7%8C%AA%E7%81%B5%E7%9A%84%E5%A4%B4)
    - [ ] 在[闪电苦力怕](https://wiki.biligame.com/mc/%E9%97%AA%E7%94%B5%E8%8B%A6%E5%8A%9B%E6%80%95)杀死[猪灵](https://wiki.biligame.com/mc/%E7%8C%AA%E7%81%B5)时掉落
    - [ ] 在其收到红石信号时或玩家穿戴其行走时扇动耳朵
- [ ] 新物品
  - [ ]  [瓶子草荚果](https://wiki.biligame.com/mc/%E7%93%B6%E5%AD%90%E8%8D%89%E8%8D%9A%E6%9E%9C)
    - [ ] 可以种植在[耕地](https://wiki.biligame.com/mc/%E8%80%95%E5%9C%B0)上。
    - [ ] 可通过[嗅探兽](https://wiki.biligame.com/mc/%E5%97%85%E6%8E%A2%E5%85%BD)挖掘获得
    - [ ] 可用于喂食[鸡](https://wiki.biligame.com/mc/%E9%B8%A1)和[鹦鹉](https://wiki.biligame.com/mc/%E9%B9%A6%E9%B9%89)
  - [ ] [锻造模板](https://wiki.biligame.com/mc/%E9%94%BB%E9%80%A0%E6%A8%A1%E6%9D%BF)
    - [ ] 可以在工作台中用7个[钻石](https://wiki.biligame.com/mc/%E9%92%BB%E7%9F%B3)、1个锻造模板和1个对应复制材料来复制1个
    - [ ] 下界合金装备制作现在需要花费一个锻造模板
    - [ ] 下界合金升级
    - [ ] 海岸盔甲纹饰
    - [ ] 沙丘盔甲纹饰
    - [ ] 眼眸盔甲纹饰
    - [ ] 雇主盔甲纹饰
    - [ ] 牧民盔甲纹饰
    - [ ] 肋骨盔甲纹饰
    - [ ] 哨兵盔甲纹饰
    - [ ] 塑造盔甲纹饰
    - [ ] 幽静盔甲纹饰
    - [ ] 猪鼻盔甲纹饰
    - [ ] 尖塔盔甲纹饰
    - [ ] 潮汐盔甲纹饰
    - [ ] 恼鬼盔甲纹饰
    - [ ] 监守盔甲纹饰
    - [ ] 向导盔甲纹饰
    - [ ] 荒野盔甲纹饰
  - [ ] [刷子](https://wiki.biligame.com/mc/%E5%88%B7%E5%AD%90)
    - [ ] 可用于清理可疑的方块
  - [ ] [陶片](https://wiki.biligame.com/mc/%E9%99%B6%E7%89%87)
    - [ ] 及其共20个变种 
  - [ ] [火把花种子](https://wiki.biligame.com/mc/%E7%81%AB%E6%8A%8A%E8%8A%B1%E7%A7%8D%E5%AD%90)
    - [ ] 可以种植在耕地上
    - [ ] 可通过嗅探兽挖掘获得
    - [ ] 可用于喂食[鸡](https://wiki.biligame.com/mc/%E9%B8%A1)、[鹦鹉](https://wiki.biligame.com/mc/%E9%B9%A6%E9%B9%89)和嗅探兽
  - [ ] [音乐唱片](https://wiki.biligame.com/mc/%E9%9F%B3%E4%B9%90%E5%94%B1%E7%89%87)Relic
    - [ ] 能够在[古迹废墟](https://wiki.biligame.com/mc/%E5%8F%A4%E8%BF%B9%E5%BA%9F%E5%A2%9F)通过刷扫[可疑的沙砾](https://wiki.biligame.com/mc/%E5%8F%AF%E7%96%91%E7%9A%84%E6%B2%99%E7%A0%BE)获得
    - [ ] 能通过[红石比较器](https://wiki.biligame.com/mc/%E7%BA%A2%E7%9F%B3%E6%AF%94%E8%BE%83%E5%99%A8)输出15格红石信号
- [ ] 新生物/实体
  - [ ] [骆驼](https://wiki.biligame.com/mc/%E9%AA%86%E9%A9%BC)
  - [ ] [嗅探兽](https://wiki.biligame.com/mc/%E5%97%85%E6%8E%A2%E5%85%BD)
  - [ ] [竹筏](https://wiki.biligame.com/mc/%E7%AB%B9%E7%AD%8F)
  - [ ] [樱花木船](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%9C%A8%E8%88%B9)
  - [ ] [樱花木运输船](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%9C%A8%E8%BF%90%E8%BE%93%E8%88%B9)
- [ ] 功能/玩法
  - [ ] ObjectTree的新实现：[樱花树](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%A0%91)
  - [ ] 自然生成[樱花树林](https://wiki.biligame.com/mc/%E6%A8%B1%E8%8A%B1%E6%A0%91%E6%9E%97)
  - [ ] 自然生成[古迹废墟](https://wiki.biligame.com/mc/%E5%8F%A4%E8%BF%B9%E5%BA%9F%E5%A2%9F)
  - [ ] [沙漠神殿](https://wiki.biligame.com/mc/%E6%B2%99%E6%BC%A0%E7%A5%9E%E6%AE%BF)更改了结构，现在会有一个填满沙子和可疑的沙子的新空间
  - [ ] [沙漠水井](https://wiki.biligame.com/mc/%E6%B2%99%E6%BC%A0%E6%B0%B4%E4%BA%95)会在其水下生成可以的沙子
  - [ ] [紫水晶块](https://wiki.biligame.com/mc/%E7%B4%AB%E6%B0%B4%E6%99%B6%E5%9D%97)在放置在幽匿感测体旁时具有共振功能
  - [ ] [苔藓块](https://wiki.biligame.com/mc/%E8%8B%94%E8%97%93%E5%9D%97)上方可以种植[甘蔗](https://wiki.biligame.com/mc/%E7%94%98%E8%94%97)和[竹子](https://wiki.biligame.com/mc/%E7%AB%B9%E5%AD%90)
  - [ ] [生物头颅](https://wiki.biligame.com/mc/%E7%94%9F%E7%89%A9%E5%A4%B4%E9%A2%85)现在可放在音符盒上，发出对应生物的空闲状态音效
  - [x] [告示牌](https://wiki.biligame.com/mc/%E5%91%8A%E7%A4%BA%E7%89%8C)相关
    - [x] 放置后可以通过与其交互来重新编辑文字
    - [x] 告示牌的两面可以分别显示独立的文字和文字颜色
    - [x] 可以使用[蜜脾](https://wiki.biligame.com/mc/%E8%9C%9C%E8%84%BE)涂蜡，涂蜡后的告示牌无法再进行编辑
  - [ ] [羊毛地毯](https://wiki.biligame.com/mc/%E5%9C%B0%E6%AF%AF)id被拆分，需要修复相关合成并自动转换旧版物品
  - [ ] [珊瑚](https://wiki.biligame.com/mc/%E7%8F%8A%E7%91%9A)id被拆分，需要修复相关合成并自动转换旧版物品
  - [ ] `minecraft:lava_cauldron`被移除，取而代之的是数据值8-15
  - [ ] [枯萎的灌木](https://wiki.biligame.com/mc/%E6%9E%AF%E8%90%8E%E7%9A%84%E7%81%8C%E6%9C%A8)可以放置在[草方块](https://wiki.biligame.com/mc/%E8%8D%89%E6%96%B9%E5%9D%97)、[菌丝体](https://wiki.biligame.com/mc/%E8%8F%8C%E4%B8%9D%E4%BD%93)、[灰化土](https://wiki.biligame.com/mc/%E7%81%B0%E5%8C%96%E5%9C%9F)和[苔藓块](https://wiki.biligame.com/mc/%E8%8B%94%E8%97%93%E5%9D%97)上
  - [ ] [幽匿尖啸体](https://wiki.biligame.com/mc/%E5%B9%BD%E5%8C%BF%E5%B0%96%E5%95%B8%E4%BD%93)在[含水](https://wiki.biligame.com/mc/%E5%90%AB%E6%B0%B4)时静音
  - [ ] 声音（振动）频率修改
  - [ ] [幽匿感测体](https://wiki.biligame.com/mc/%E5%B9%BD%E5%8C%BF%E6%84%9F%E6%B5%8B%E4%BD%93)相关：
    - [ ] 会强充能下方的方块
    - [ ] 激活状态的持续时长由40游戏刻改为30游戏刻
    - [ ] 冷却状态的持续时长由1游戏刻改为10游戏刻
  - [ ] 锻造台现在需要锻造模板才能进行合成
  - [x] [盾牌](https://wiki.biligame.com/mc/%E7%9B%BE%E7%89%8C)可以添加旗帜图案
    - [ ] 实现[盾牌](https://wiki.biligame.com/mc/%E7%9B%BE%E7%89%8C)与[旗帜](https://wiki.biligame.com/mc/%E6%97%97%E5%B8%9C)的合成配方
  - [ ] [监守者](https://wiki.biligame.com/mc/%E7%9B%91%E5%AE%88%E8%80%85)可以能检测到[紫水晶块](https://wiki.biligame.com/mc/%E7%B4%AB%E6%B0%B4%E6%99%B6%E5%9D%97)的共振
  - [ ] [村庄英雄](https://wiki.biligame.com/mc/%E6%9D%91%E5%BA%84%E8%8B%B1%E9%9B%84)效果现在拥有粒子颜色
